# Help

In [43]:
# ?<function name>
?print

# Assignment

In [28]:
x <- 1:20
print(x)

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20


# Data Types

In [22]:
# class() to check data types
class("Hello World")
class(TRUE)
class(100)
class(100L)
class(3+2i)

[1] "character"

[1] "logical"

[1] "numeric"

[1] "integer"

[1] "complex"

# Objects
### Vectors, Matrices, and Array

In [27]:
# create a vector
v <- c(1, 2, 3)
print(v)

[1] 1 2 3


In [35]:
# Vectorized Operations of Vectors
x <- 1:4; y <- 6:9
x*y

[1]  6 14 24 36

In [5]:
# create an empty vector
vector()

logical(0)

In [29]:
# create a matrix
m <- matrix(1:6, nrow = 2, ncol = 3, dimnames = list(c("a", "b"), c("c", "d", "e")))
print(m)

  c d e
a 1 3 5
b 2 4 6


In [8]:
# check the dimension of the matrix
dim(m)

[1] 2 3

In [36]:
# bind two vectors
x <- 1:3; y <- 10:12
cbind(x, y)
rbind(x, y)

x y 
[1,] 1 10
[2,] 2 11
[3,] 3 12

[,1] [,2] [,3]
x  1    2    3  
y 10   11   12

In [38]:
# Vectorized Operations of Matrices
x <- matrix(1:4, 2, 2); y <- matrix(rep(10, 4), 2, 2)
x * y      ## element-wise multiplication
x %*% y    ## true matrix multiplication

[,1] [,2]
[1,] 10   30  
[2,] 20   40

[,1] [,2]
[1,] 40   40  
[2,] 60   60

In [26]:
# create an array (can be more than two dimensions)
a <- array(c("green", "yellow"), dim = c(3, 3, 2))
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 

, , 2

     [,1]     [,2]     [,3]    
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green" 
[3,] "yellow" "green"  "yellow"



### Lists

In [30]:
# can be different data types
li <- list(c(1, 2, 3), c("a", "b", "c", "d"), 4+6i)
print(li)

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c" "d"

[[3]]
[1] 4+6i



### Factors

In [31]:
x <- factor(c("yes", "yes", "no", "yes", "no"), levels = c("yes", "no"))
print(x)

[1] yes yes no  yes no 
Levels: yes no


### Data Frames

In [32]:
x <- data.frame(column1 = 1:4, column2 = c(T, T, F, F))
print(x)

  column1 column2
1       1    TRUE
2       2    TRUE
3       3   FALSE
4       4   FALSE


In [19]:
# count the number of rows and columns
nrow(x)
ncol(x)

[1] 4

[1] 2

# Check if Missing Values Exist

In [33]:
is.na(c(1, 2, NA, 4, 5))
is.nan(NaN)

[1] FALSE FALSE  TRUE FALSE FALSE

[1] TRUE

# Subsetting
### Subsetting Vectors

In [1]:
x <- c("a", "b", "c", "c", "d", "a")
x[2]
x[1:4]
x[x > "a"]

[1] "b"

[1] "a" "b" "c" "c"

[1] "b" "c" "c" "d"

### Subsetting Lists

In [8]:
x <- list(foo = 1:4, bar = 0.6)
# [ always returns an object of the same class as the origin;
# can be used to select more than one element (there is one exception)
x[1]

$foo
[1] 1 2 3 4

In [9]:
# [[ is used to extract elements of a list or a data frame;
# it can only be used to extract a single element and the class
# of the retured object will not necessarily be a list or data frame
x[[1]]

[1] 1 2 3 4

In [10]:
# $ is used to extract elements of a list or data frame by name;
# semantics are similar to that of [[
x$bar

[1] 0.6

In [11]:
x[["bar"]]

[1] 0.6

In [12]:
x["bar"]

$bar
[1] 0.6

In [13]:
y <- list(foo = 1:4, bar = 0.6, baz = "hello")
y[c(1, 3)]

$foo
[1] 1 2 3 4

$baz
[1] "hello"

In [14]:
# subsetting nested elements of a list
z <- list(a = list(10, 12, 14), b = c(3.14, 2.81))
z[[c(1, 3)]]
z[[c(2, 1)]]

[1] 14

[1] 3.14

### Subsetting Matrices

In [19]:
x <- matrix(1:6, 2, 3)
x[1, 2]
x[2, ]
class(x[2, ])
# still a matrix
x[2, , drop = FALSE]
class(x[2, , drop = FALSE])

[1] 3

[1] 2 4 6

[1] "integer"

[,1] [,2] [,3]
[1,] 2    4    6

[1] "matrix"

### Subsetting Data Frames

In [20]:
# see 3_Cleaning Data part

### Removing Missing Values 

In [23]:
x <- c(1, 2, NA, 4, NA, 5)
bad <- is.na(x)
x <- x[!bad]
print(x)

[1] 1 2 4 5


In [21]:
x <- c(1, 2, NA, 4, NA, 5)
y <- c("a", "b", NA, "d", NA, "f")
good <- complete.cases(x, y)
good
x[good]
y[good]

[1]  TRUE  TRUE FALSE  TRUE FALSE  TRUE

[1] 1 2 4 5

[1] "a" "b" "d" "f"

In [25]:
airquality[1:6, ]

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

In [26]:
good <- complete.cases(airquality)
airquality[good, ][1:6, ]

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
7 23    299      8.6 65   5     7  
8 19     99     13.8 59   5     8

# Control Structures
### If-else

In [ ]:
if(x > 3) {
    y <- 10
} else if{
    y <- 5
} else {
    y <- 0
}

In [ ]:
# can alse be written as
y <- if(x > 3) {
    10
} else if{
    5
} else {
    0
}

### For loops

In [27]:
for(i in 1:10) {
    print(i)
} 

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [30]:
x <- matrix(1:6, 2, 3)

for(i in seq_len(nrow(x))) {
    for(j in seq_len(ncol(x))) {
        print(x[i, j])
    }
}

[1] 1
[1] 3
[1] 5
[1] 2
[1] 4
[1] 6


### While loops

In [31]:
count <- 0
while(count < 10) {
    print(count)
    count <- count + 1
}

[1] 0
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9


# Functions

In [34]:
f <- function(a, b) {
    c = a ^ 2
    d = b * 2
    print(c + d)
}

f(5, 6)

[1] 37


# Dates and Times

In [39]:
# dates are represented by the "Date" class
# dates are stored internally as the number of days since 1970-01-01
x <- as.Date("1970-01-01")
x
class(x)

unclass(x)

[1] "1970-01-01"

[1] "Date"

In [41]:
# times are represented by the "POSIXct" or the "POSIXlt" class
# times are stored internally as the number of seconds since 1970-01-01
# POSIXct is a very large integer
# POSIXlt is a list containing a bunch of useful information
x <- Sys.time()
x

p <- as.POSIXlt(x)
names(unclass(p))
p$sec

[1] "2018-03-19 20:59:37 CST"

[1] "sec"    "min"    "hour"   "mday"   "mon"    "year"   "wday"   "yday"  
 [9] "isdst"  "zone"   "gmtoff"

[1] 37.05184

In [42]:
x <- Sys.time()
x    # already in POSIXct format
unclass(x)

[1] "2018-03-19 21:01:25 CST"

[1] 1521464486

In [50]:
# if your dates are written in a different format
datestring <- c("January 10, 2012 10:40", 
                "December 9, 2011 9:10")
x <- strptime(datestring, "%B %d, %Y %H:%M")
x
class(x)

[1] "2012-01-10 10:40:00 CST" "2011-12-09 09:10:00 CST"

[1] "POSIXlt" "POSIXt"

In [51]:
# operations
x <- as.POSIXct("2012-10-25 01:00:00")
y <- as.POSIXct("2012-10-25 06:00:00", tz = "GMT")
y-x

Time difference of 13 hours

# Simulation

In [64]:
# generate random Normal variates with a given mean and standard deviation
x <- rnorm(10)
print(x)

y <- rnorm(n = 10, mean = 20, sd = 2)
print(y)

# get an overview
summary(x)
str(x)

 [1]  0.1283861  1.0181200 -0.2555737 -0.3025410  1.6151907 -0.7737134
 [7]  0.4240024 -0.5839470  0.4150357 -1.5452617
 [1] 18.96250 19.44042 22.01491 19.06086 20.59579 19.16441 18.29924 21.37809
 [9] 19.07961 22.69637


    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-1.54526 -0.51360 -0.06359  0.01397  0.42176  1.61519 

 num [1:10] 0.128 1.018 -0.256 -0.303 1.615 ...


In [56]:
# set.seed ensures reproduciblity
set.seed(100)
rnorm(5)

rnorm(5)

set.seed(100)
rnorm(5)

[1] -0.50219235  0.13153117 -0.07891709  0.88678481  0.11697127

[1]  0.3186301 -0.5817907  0.7145327 -0.8252594 -0.3598621

[1] -0.50219235  0.13153117 -0.07891709  0.88678481  0.11697127

In [58]:
# generate Poisson data
rpois(n = 10, lambda = 1)

# cumulative distribution
ppois(q = 2, lambda = 2)    # Pr(x <= 2)
ppois(4, 2)                 # Pr(x <= 4)
ppois(6, 2)                 # Pr(x <= 6)

[1] 1 1 1 2 1 0 2 2 1 0

[1] 0.6766764

[1] 0.947347

[1] 0.9954662

In [66]:
set.seed(1)
sample(1:10, 4)
sample(1:10, 4)

sample(letters, 5)

sample(1:10)                  # permutation (取後不放回)
sample(1:10, replace = TRUE)  # sample w/replacement (取後放回)

[1] 3 4 5 7

[1] 3 9 8 5

[1] "q" "b" "e" "x" "p"

[1]  4  7 10  6  9  2  8  3  1  5

[1] 2 3 4 1 4 9 4 5 6 5