# Loop Functions
The actual looping is done internally in C code, so these functions will work faster.

|Loop Function|Function|
|:-|:-|
|lapply|Loop over a list and evaluate a function on each element.|
|sapply|Same as lapply but try to simplify the result.|
|vapply|Whereas sapply tries to 'guess' the correct format of the result, vapply allows you to specify it explicitly.|
|apply|Apply a function over the margins of an array.|
|tapply|Apply a function over subsets of a vector.|
|mapply|Multivariate version of lapply.|
|split|Split takes a vector or other objects and splits it into groups determined by a factor or list of factors.|

## lapply
Loop over a list and evaluate a function on each element.

In [43]:
str(lapply)

function (X, FUN, ...)  


Three arguments:
- X: a list
- FUN: a function
- other arguments

In [2]:
x <- list(a = 1:5, b = rnorm(10))
lapply(x, mean)

$a
[1] 3

$b
[1] -0.2658745

In [7]:
# if X is not a list, it will be coerced to a list using as.list()
x <- 1:4
lapply(x, runif, min = 0, max = 10)

[[1]]
[1] 6.054645

[[2]]
[1] 3.953318 9.892902

[[3]]
[1] 6.560789 4.427325 9.403188

[[4]]
[1] 6.086776 5.012243 7.670875 2.185693

In [8]:
# make use of anonymous functions
x <- list(a = matrix(1:4, 2, 2), b = matrix(1:6, 3, 2))
lapply(x, function(elt) elt[,1])

$a
[1] 1 2

$b
[1] 1 2 3

## sapply
Same as lapply but try to simplify the result if possible.

- If the result is a list where every element is length 1, then a vector is returned.
- If the result is a list where every element is a vector of the same length (> 1), a matrix is returned.
- If it can’t figure things out, a list is returned

In [9]:
x <- list(a = 1:4, b = rnorm(10), c = rnorm(20, 1), d = rnorm(100, 5))
lapply(x, mean)

$a
[1] 2.5

$b
[1] 0.1176109

$c
[1] 1.175906

$d
[1] 5.1322

In [11]:
print(sapply(x, mean))

        a         b         c         d 
2.5000000 0.1176109 1.1759061 5.1322004 


## vapply
Use vapply to specify the format explicitly.

In [19]:
print(vapply(x, mean, numeric(1)))

        a         b         c         d 
2.5000000 0.1176109 1.1759061 5.1322004 


## apply
Apply a function over the margins of an array.

- It is most often used to apply a function to the rows or columns of a matrix.
- It can be used with general arrays, e.g. taking the average of an array of matrices.
- It is not really faster than writing a loop, but it works in one line!

In [42]:
str(apply)

function (X, MARGIN, FUN, ...)  


- **`X`** is an array
- **`MARGIN`** is an integer vector indicating which margins should be “retained”.
- **`FUN`** is a function to be applied.
- ... is for other arguments to be passed to **`FUN`**.

In [21]:
x <- matrix(rnorm(200), 20, 10)
apply(x, 2, mean)
apply(x, 1, sum)

[1]  0.264191697 -0.027318293  0.111754703 -0.061889794 -0.272468150
 [6]  0.435640738 -0.001119577 -0.355067651 -0.226310869  0.075366571

[1] -1.1149724  1.0617720 -5.2034755  0.1962028  0.5665848  2.5019974
 [7]  0.0536623 -1.1663138 -1.9642241  3.6896174  3.4537020 -1.0871045
[13]  1.8587927 -5.4720983 -2.5192605  4.3365567 -0.1985724 -1.8273778
[19] -3.4122440  5.1023429

In [22]:
# However, for sums and means of matrix dimensions, we have some shortcuts.
# rowSums = apply(x, 1, sum)
# rowMeans = apply(x, 1, mean)
# colSums = apply(x, 2, sum)
# colMeans = apply(x, 2, mean)
rowSums(x)

[1] -1.1149724  1.0617720 -5.2034755  0.1962028  0.5665848  2.5019974
 [7]  0.0536623 -1.1663138 -1.9642241  3.6896174  3.4537020 -1.0871045
[13]  1.8587927 -5.4720983 -2.5192605  4.3365567 -0.1985724 -1.8273778
[19] -3.4122440  5.1023429

In [23]:
x <- matrix(rnorm(200), 20, 10)
apply(x, 1, quantile, probs = c(0.25, 0.75))

[,1]        [,2]       [,3]       [,4]       [,5]       [,6]      
25% -1.26588308 -1.5716399 -0.9697316 -0.7560281 -0.4894893 -0.1415978
75% -0.04466169  0.2496246  0.2707867  0.1404011  0.6845154  0.5346277
    [,7]       [,8]      [,9]      [,10]      [,11]      [,12]      [,13]     
25% -1.0255180 0.2852734 0.2619959 -0.3601064 -1.1072965 -0.0673048 -0.3866871
75%  0.9245223 1.0518022 1.1929142  0.7334745  0.4720414  0.9800842  1.1324641
    [,14]      [,15]      [,16]      [,17]      [,18]      [,19]      
25% -1.0863424 -0.6065425 -0.9444925 -0.1211762 -1.3992334 -0.08954942
75%  0.2695238  0.9869443  0.2148389  0.7564675  0.7046646  0.57625922
    [,20]     
25% -0.7340517
75%  0.8407462

In [24]:
a <- array(rnorm(2 * 2 * 10), c(2, 2, 10))
apply(a, c(1, 2), mean)
rowMeans(a, dims = 2)

[,1]        [,2]      
[1,] 0.005414237  0.1636575
[2,] 0.260209521 -0.4407803

[,1]        [,2]      
[1,] 0.005414237  0.1636575
[2,] 0.260209521 -0.4407803

## tapply
Apply a function over subsets of a vector.

In [41]:
str(tapply)

function (X, INDEX, FUN = NULL, ..., default = NA, simplify = TRUE)  


- **`X`** is a vector.
- **`INDEX`** is a factor or a list of factors (or else they are coerced to factors).
- **`FUN`** is a function to be applied.
- ... contains other arguments to be passed **`FUN`**
- **`simplify`**, should we simplify the result?

In [38]:
x <- c(rnorm(10), runif(10), rnorm(10, 1))
f <- gl(3, 10)
print(f)
print(tapply(x, f, mean))
print(tapply(x, f, mean, simplify = F))

 [1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
Levels: 1 2 3
         1          2          3 
-0.5504630  0.4189813  1.4164064 
$`1`
[1] -0.550463

$`2`
[1] 0.4189813

$`3`
[1] 1.416406



In [39]:
print(tapply(x, f, range))

$`1`
[1] -3.2615202  0.7038547

$`2`
[1] 0.03530037 0.84991271

$`3`
[1] -1.478466  3.080520



## mapply
Multivariate version of lapply.

In [40]:
str(mapply)

function (FUN, ..., MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE)  


- **`FUN`** is a function to apply.
- ... contains arguments to apply over.
- **`MoreArgs`** is a list of other arguments to **`FUN`**.
- **`SIMPLIFY`** indicates whether the result should be simplified.

In [45]:
# The following is tedious to type:
# list(rep(1, 4), rep(2, 3), rep(3, 2), rep(4, 1))
# Instead we can do
print(mapply(rep, 1:4, 4:1))

[[1]]
[1] 1 1 1 1

[[2]]
[1] 2 2 2

[[3]]
[1] 3 3

[[4]]
[1] 4



In [47]:
# Vectorizing a function
noise <- function(n, mean, sd) {
rnorm(n, mean, sd)
}

noise(5, 1, 2)

mapply(noise, 1:5, 1:5, 2)

# which is the same as
# list(noise(1, 1, 2), noise(2, 2, 2),
#      noise(3, 3, 2), noise(4, 4, 2),
#      noise(5, 5, 2))

[1]  6.2775050 -2.1623025  1.3341160  2.8287204 -0.4259282

[[1]]
[1] 0.9871351

[[2]]
[1] 4.798275 2.751019

[[3]]
[1] 0.7385036 1.3470631 2.7884028

[[4]]
[1] 5.465034 5.409988 2.326431 4.269666

[[5]]
[1] 5.883341 5.966623 6.412617 8.707788 2.976017

## split
split takes a vector or other objects and splits it into groups determined by a factor or list of
factors.
Works well with lapply.

In [48]:
str(split)

function (x, f, drop = FALSE, ...)  


- **`x`** is a vector (or list) or data frame.
- **`f`** is a factor (or coerced to one) or a list of factors.
- **`drop`** indicates whether empty factors levels should be dropped.

In [49]:
x <- c(rnorm(10), runif(10), rnorm(10, 1))
f <- gl(3, 10)
split(x, f)

$`1`
 [1]  1.2746766 -0.1627360  0.5334254  1.8594423 -0.1576057 -0.3332478
 [7]  0.6377531  0.8639712  2.4551404  1.8627963

$`2`
 [1] 0.43273831 0.51287461 0.39093339 0.70888843 0.67084534 0.55463545
 [7] 0.91154367 0.98442399 0.79449121 0.02166671

$`3`
 [1]  2.222814  1.425659 -0.268915  1.237883 -0.219132  2.669714  1.826882
 [8]  1.469578 -0.171634  1.650005

In [50]:
# work with lapply because the first argument in lapply is a list
lapply(split(x, f), mean)

$`1`
[1] 0.8833616

$`2`
[1] 0.5983041

$`3`
[1] 1.184286

In [53]:
# splitting a data frame
head(airquality)
s <- split(airquality, airquality$Month)
print(lapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Wind")])))

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

$`5`
   Ozone  Solar.R     Wind 
      NA       NA 11.62258 

$`6`
    Ozone   Solar.R      Wind 
       NA 190.16667  10.26667 

$`7`
     Ozone    Solar.R       Wind 
        NA 216.483871   8.941935 

$`8`
   Ozone  Solar.R     Wind 
      NA       NA 8.793548 

$`9`
   Ozone  Solar.R     Wind 
      NA 167.4333  10.1800 



In [57]:
sapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Wind")]))
sapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Wind")],
na.rm = TRUE))

5        6         7          8        9       
Ozone         NA        NA         NA       NA       NA
Solar.R       NA 190.16667 216.483871       NA 167.4333
Wind    11.62258  10.26667   8.941935 8.793548  10.1800

5         6         7          8          9        
Ozone    23.61538  29.44444  59.115385  59.961538  31.44828
Solar.R 181.29630 190.16667 216.483871 171.857143 167.43333
Wind     11.62258  10.26667   8.941935   8.793548  10.18000

In [60]:
# splitting on more than one level
x <- rnorm(10)
f1 <- gl(2, 5)
f2 <- gl(5, 2)
interaction(f1, f2)
str(split(x, list(f1, f2)))
# empty levels can be dropped
str(split(x, list(f1, f2), drop = TRUE))

[1] 1.1 1.1 1.2 1.2 1.3 2.3 2.4 2.4 2.5 2.5
Levels: 1.1 2.1 1.2 2.2 1.3 2.3 1.4 2.4 1.5 2.5

List of 10
 $ 1.1: num [1:2] -2.069 0.996
 $ 2.1: num(0) 
 $ 1.2: num [1:2] 0.906 -1.785
 $ 2.2: num(0) 
 $ 1.3: num -1.76
 $ 2.3: num -1.1
 $ 1.4: num(0) 
 $ 2.4: num [1:2] -0.212 -0.312
 $ 1.5: num(0) 
 $ 2.5: num [1:2] -0.329 -0.237
List of 6
 $ 1.1: num [1:2] -2.069 0.996
 $ 1.2: num [1:2] 0.906 -1.785
 $ 1.3: num -1.76
 $ 2.3: num -1.1
 $ 2.4: num [1:2] -0.212 -0.312
 $ 2.5: num [1:2] -0.329 -0.237
